A: https://gatsunime.org/
ABPindo/indonesianadblockrules pull request #254
Opened 2022-02-10 07:33 UTC by felippesantos46

Block adservers + Hide modal at https://gatsunime.org/

Screenshots: 
<img width="1099" alt="Screenshot 2022-02-10 at 08 32 55" src="https://user-images.githubusercontent.com/65717387/153359007-9f28145d-bd27-45d6-b4d4-d0b023b958ec.png">
<img width="1101" alt="Screenshot 2022-02-10 at 08 32 26" src="https://user-images.githubusercontent.com/65717387/153358949-f4b4e792-5ed1-4d90-a4ef-cb8bd66dfce5.png">

Maybe this filter can be moved to the specific block side, Discord is widely used within the pages.
On the other hand I've never seen this cdn before. If you think other webpages may crash we could go for: `||discordapp.com^$third-party,domain=gatsunime.org`
<img width="829" alt="Screenshot 2022-02-10 at 08 32 03" src="https://user-images.githubusercontent.com/65717387/153358896-59367a7d-b405-46ce-8022-3767567b687b.png">

2022-02-10 10:17 UTC, gmarcher requested changes
ah i see, thats smart move from web dev, using attachment as source
` ||discordapp.com^$third-party` it's not adv domain, discord cdn and as per Easylist policy no add
how about `##a[target="_blank"][rel^="noopener noreferrer"] > img[src$=".gif"]`

2022-02-10 10:18 UTC, gmarcher approved these changes

2022-02-11 09:06 UTC, felippesantos46 commented
> ah i see, thats smart move from web dev, using attachment as source ` ||discordapp.com^$third-party` it's not adv domain, discord cdn and as per Easylist policy no add how about `##a[target="_blank"][rel^="noopener noreferrer"] > img[src$=".gif"]`

Completely agreed. I've made the proposed changes 😄 
Thank you and have a good day !

2022-02-11 11:10 UTC, merged

2022-02-11 11:31 UTC, gmarcher commented
Have a good day too!