A: otakudesu.bid
ABPindo/indonesianadblockrules pull request #375
Opened 2022-12-22 09:23 UTC by eporubin

Popping ads on top of the page, bottom and top banners within the page on mobile version.
![image](https://user-images.githubusercontent.com/33602691/209101894-b633d2ca-8eeb-4253-b7b6-70073abb4d41.png)

Thank you

2022-12-23 21:22 UTC, gmarcher requested changes

2022-12-23 21:22 UTC, gmarcher commented on src/advert/specific_hide.txt
> +otakudesu.bid,nanimex.in##.iklan
![image](https://user-images.githubusercontent.com/12405001/209142753-6259c221-3887-4cd8-aa75-1abd335a50e6.png)
`##.iklan` dan `###iklanbawah`
sudah ada di general_hide filter, apakah tidak terblokir? what browser do you use?

2022-12-23 21:22 UTC, gmarcher commented on src/advert/specific_hide.txt
> +otakudesu.bid##.box_item_ads_popup
yes, thank you. without domain, we can move it to general_hide `##.box_item_ads_popup`

2022-12-26 18:45 UTC, eporubin commented on src/advert/specific_hide.txt
> +otakudesu.bid,nanimex.in##.iklan
I checked and its all solved now, thanks I usually test on Chrome with ABP extension, Samsung Internet with ABP and ABB(for mobile). 
Thank you for looking into it and fixing it.

2022-12-26 18:46 UTC, eporubin commented on src/advert/specific_hide.txt
> +otakudesu.bid##.box_item_ads_popup
I see you moved it already, and it helps removing the ads. Thank you

2022-12-26 18:49 UTC, closed without merging